### ISSUE TITLE
설정 창의 시간표 수정 부분이 이상하게 보여요

### ISSUE THREAD

**Issue by kimkyumbi** [baekteun/TodayWhat-new#130]
### Describe

설정 창의 시간표 수정 부분이 이상하게 보여요
![image](https://github.com/baekteun/TodayWhat-new/assets/130046132/3a071f0e-5a4d-40d3-a2b3-e8ac22aba5df)

**Comment by baekteun** [comment]
@kimkyumbi 해당 이슈 해결했어요, 문의 감사합니다 👍
