### ISSUE TITLE
학교 설정하는 화면

### ISSUE THREAD

**Issue by minaje0917** [baekteun/TodayWhat-new#3]
학교 설정하는 화면에서 스크롤도 안되고 키보드도 안 내려가요!!

**Comment by baekteun** [comment]
o0o

**Comment by baekteun** [comment]
사태 분석해보겠습니다!

**Comment by baekteun** [comment]
오늘뭐임 iOS 1.1.1에 해당 오류를 해결했습니다!
이슈 감사합니다!

AppStore - https://apps.apple.com/kr/app/%EC%98%A4%EB%8A%98-%EB%AD%90%EC%9E%84/id1629567018
